version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
      - db-network
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/dockerapp
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - db-network
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dockerapp

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  mongodb_data: